version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - db-data:/app/data  # Persist the database file
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
  db-data:  # Add a volume for the database